name: Deploy to EC2

on:
  push:
    branches:
      - main  # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute remote commands on EC2
        uses: appleboy/ssh-action@v0.1.11
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |    
            cd /home/ubuntu &&
            echo "Hello github Actions" >hello.txt

